package org.team2059.Lintilla.commands;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj2.command.Command;
import org.team2059.Lintilla.Constants;
import org.team2059.Lintilla.RobotContainer;
import org.team2059.Lintilla.subsystems.collector.Collector;
import org.team2059.Lintilla.subsystems.drivetrain.Drivetrain;
import org.team2059.Lintilla.subsystems.shooter.ShooterBase;

import static edu.wpi.first.units.Units.RPM;
import static org.team2059.Lintilla.Constants.ShooterConstants.SPINUP_TOLERANCE_RPM;
import static org.team2059.Lintilla.Constants.VisionConstants.getHubTranslation;

/**
 * Command to spin the shooters up at a specific velocity (or calculate velocity based on distance to hub) and shoot
 * when a certain tolerance is reached.
 */
public class SpinupAndShootCommand extends Command {
	// We depend on these subsystems for certain methods & calculations
	private final ShooterBase shooterBase;
	private final Collector collector;
	private final Drivetrain drivetrain;

	// Holds our desired speeds
	private double desiredRPM;

	private boolean desiredRPMHardcoded;

	/**
	 * Constructor for distance-based shots (shoots on the fly)
	 *
	 * @param drivetrain  the Drivetrain subsystem
	 * @param shooterBase the ShooterBase subsystem
	 * @param collector   the Collector subsystem (so we can run the conveyor)
	 */
	public SpinupAndShootCommand(Drivetrain drivetrain, ShooterBase shooterBase, Collector collector) {
		this.shooterBase = shooterBase;
		this.drivetrain = drivetrain;
		this.collector = collector;

		// Begin by precalculating the distance to from the shooter to the hub
		this.desiredRPM = shooterBase.getTargetRpm(shooterBase.currentDistanceToTarget);
		this.desiredRPMHardcoded = false;

		addRequirements(this.shooterBase);
	}

	/**
	 * Constructor for shots at specific RPMs
	 *
	 * @param drivetrain  the Drivetrain subsystem
	 * @param shooterBase the ShooterBase subsystem
	 * @param collector   the Collector subsystem (so we can run the conveyor)
	 * @param desiredRPM  the desired speeds in RPM
	 */
	public SpinupAndShootCommand(Drivetrain drivetrain, ShooterBase shooterBase, Collector collector, double desiredRPM) {
		this.shooterBase = shooterBase;
		this.drivetrain = drivetrain;
		this.collector = collector;

		this.desiredRPM = desiredRPM;
		this.desiredRPMHardcoded = true;

		addRequirements(this.shooterBase);
	}

	@Override
	public void execute() {

		// If the desired RPM is not hardcoded, we use our lookup table with the
		// latest distance that was published to shooterBase.
		if (!desiredRPMHardcoded) {
			if (!DriverStation.isAutonomous()) {
				// In teleop, use the distance generated by the TeleopDriveCommand
				double distanceMeters = shooterBase.currentDistanceToTarget;
				desiredRPM = shooterBase.getTargetRpm(distanceMeters);
			} else {
				// In auto, calculate the distance ourselves
				double distanceMeters = getHubTranslation().getDistance(RobotContainer.drivetrain.getEstimatedPose().getTranslation());
				desiredRPM = shooterBase.getTargetRpm(distanceMeters);
			}
		}

		// Set the two flywheels to the desired RPM, whether it's hardcoded or
		// not, it doesn't matter at this point in execution.
		shooterBase.leftShooter.setFlywheelRpm(desiredRPM);
		shooterBase.rightShooter.setFlywheelRpm(desiredRPM);

		// If we're using hardcoded RPM, we don't need to check whether or not we're aimed.
		// Otherwise, we must check our aiming so we don't deliberately miss shots.
		if (desiredRPMHardcoded) {
			if (Math.abs(shooterBase.leftShooterInputs.flywheelVelocity.in(RPM) - desiredRPM) <= SPINUP_TOLERANCE_RPM) {
				// Left shooter is within tolerance. Spin indexer
				shooterBase.leftShooter.setIndexerSpeed(Constants.ShooterConstants.INDEXER_SPEED_WHILE_SHOOTING);
				collector.io.setConveyorSpeed(Constants.ShooterConstants.CONVEYOR_SPEED_WHILE_SHOOTING);
			}
			if (Math.abs(shooterBase.rightShooterInputs.flywheelVelocity.in(RPM) - desiredRPM) <= SPINUP_TOLERANCE_RPM) {
				// Right shooter is within tolerance. Spin indexer
				shooterBase.rightShooter.setIndexerSpeed(Constants.ShooterConstants.INDEXER_SPEED_WHILE_SHOOTING);
				collector.io.setConveyorSpeed(Constants.ShooterConstants.CONVEYOR_SPEED_WHILE_SHOOTING);
			}
		} else {
			if (Math.abs(shooterBase.leftShooterInputs.flywheelVelocity.in(RPM) - desiredRPM) <= SPINUP_TOLERANCE_RPM) {
				// Left shooter is within tolerance. Spin indexer
				shooterBase.leftShooter.setIndexerSpeed(Constants.ShooterConstants.INDEXER_SPEED_WHILE_SHOOTING);
				collector.io.setConveyorSpeed(Constants.ShooterConstants.CONVEYOR_SPEED_WHILE_SHOOTING);
			}
			if (Math.abs(shooterBase.rightShooterInputs.flywheelVelocity.in(RPM) - desiredRPM) <= SPINUP_TOLERANCE_RPM) {
				// Right shooter is within tolerance. Spin indexer
				shooterBase.rightShooter.setIndexerSpeed(Constants.ShooterConstants.INDEXER_SPEED_WHILE_SHOOTING);
				collector.io.setConveyorSpeed(Constants.ShooterConstants.CONVEYOR_SPEED_WHILE_SHOOTING);
			}
		}
	}

	@Override
	public boolean isFinished() {
		return false;
	}

	@Override
	public void end(boolean interrupted) {
		// Stop everything that we used
		shooterBase.leftShooter.stopIndexer();
		shooterBase.leftShooter.stopFlywheel();
		shooterBase.rightShooter.stopIndexer();
		shooterBase.rightShooter.stopFlywheel();
		collector.io.stopConveyor();
	}
}
