package org.team2059.Lintilla.commands;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj2.command.Command;
import org.team2059.Lintilla.subsystems.conveyor.Conveyor;
import org.team2059.Lintilla.subsystems.drivetrain.Drivetrain;
import org.team2059.Lintilla.subsystems.shooter.ShooterBase;

import static edu.wpi.first.units.Units.RPM;
import static org.team2059.Lintilla.Constants.ConveyorConstants.SHOOTING_CONVEYOR_SPEED;
import static org.team2059.Lintilla.Constants.ShooterConstants.INDEXER_SPEED_WHILE_SHOOTING;
import static org.team2059.Lintilla.Constants.ShooterConstants.SPINUP_TOLERANCE_RPM;
import static org.team2059.Lintilla.Constants.VisionConstants.getHubTranslation;

/**
 * Command to spin the shooters up at a specific velocity (or calculate velocity based on distance to hub) and shoot
 * when a certain tolerance is reached.
 * <p>
 * Makes the collector angled 45 degrees as well as running the rollers so we have a consistent stream of balls.
 */
public class SpinupAndShootCommand extends Command {
	// We depend on these subsystems for certain methods & calculations
	private final ShooterBase shooterBase;
	private final Conveyor conveyor;
	private final Drivetrain drivetrain;
	// Holds our desired speeds
	private double desiredRPM;
	private boolean desiredRPMHardcoded;

	/**
	 * Constructor for distance-based shots (shoots on the fly)
	 *
	 * @param drivetrain  the Drivetrain subsystem
	 * @param shooterBase the ShooterBase subsystem
	 * @param conveyor    the Conveyor subsystem (so we can run the conveyor)
	 */
	public SpinupAndShootCommand(Drivetrain drivetrain, ShooterBase shooterBase, Conveyor conveyor) {
		this.shooterBase = shooterBase;
		this.drivetrain = drivetrain;
		this.conveyor = conveyor;

		// Begin by precalculating the distance to from the shooter to the hub
		this.desiredRPM = shooterBase.getTargetRpm(shooterBase.currentDistanceToTarget);
		this.desiredRPMHardcoded = false;

		addRequirements(this.shooterBase, this.conveyor);
	}

	/**
	 * Constructor for shots at specific RPMs
	 *
	 * @param drivetrain  the Drivetrain subsystem
	 * @param shooterBase the ShooterBase subsystem
	 * @param conveyor    the Conveyor subsystem (so we can run the conveyor)
	 * @param desiredRPM  the desired speeds in RPM
	 */
	public SpinupAndShootCommand(Drivetrain drivetrain, ShooterBase shooterBase, Conveyor conveyor, double desiredRPM) {
		this.shooterBase = shooterBase;
		this.drivetrain = drivetrain;
		this.conveyor = conveyor;

		this.desiredRPM = desiredRPM;
		this.desiredRPMHardcoded = true;

		addRequirements(this.shooterBase, this.conveyor);
	}

	@Override
	public void initialize() {
//		collector.io.setIntakeSpeed(SHOOTING_ROLLER_SPEED);
//		collector.io.setTiltPosition(THRUBORE_SHOOTING);
	}

	@Override
	public void execute() {

		// If the desired RPM is not hardcoded, we use our lookup table with the
		// latest distance that was published to shooterBase.
		if (!desiredRPMHardcoded) {
			if (!DriverStation.isAutonomous()) {
				// In teleop, use the distance generated by the TeleopDriveCommand
				double distanceMeters = shooterBase.currentDistanceToTarget;
				desiredRPM = (shooterBase.addFivePercent)
				  ? shooterBase.getTargetRpm(distanceMeters * 1.05)
				  : shooterBase.getTargetRpm(distanceMeters);
			} else {
				// In auto, calculate the distance ourselves
				double distanceMeters = getHubTranslation().getDistance(Drivetrain.getInstance().getEstimatedPose().getTranslation());
				desiredRPM = (shooterBase.addFivePercent)
				  ? shooterBase.getTargetRpm(distanceMeters * 1.05)
				  : shooterBase.getTargetRpm(distanceMeters);
			}
		}

		// Set the two flywheels to the desired RPM, whether it's hardcoded or
		// not, it doesn't matter at this point in execution.
		shooterBase.leftShooter.setFlywheelRpm(desiredRPM);
		shooterBase.rightShooter.setFlywheelRpm(desiredRPM);

		double leftCurrentVelocityRPM = shooterBase.leftShooterInputs.flywheelVelocity.in(RPM);
		double rightCurrentVelocityRPM = shooterBase.rightShooterInputs.flywheelVelocity.in(RPM);

		// If we're using hardcoded RPM, we don't need to check whether or not we're aimed.
		// Otherwise, we must check our aiming so we don't deliberately miss shots.
		if (desiredRPMHardcoded) {
			if (Math.abs(leftCurrentVelocityRPM - desiredRPM) <= SPINUP_TOLERANCE_RPM) {
				// Left shooter is within tolerance. Spin indexer
				shooterBase.leftShooter.setIndexerSpeed(INDEXER_SPEED_WHILE_SHOOTING);
				conveyor.io.setConveyorSpeed(SHOOTING_CONVEYOR_SPEED);
			}
			if (Math.abs(rightCurrentVelocityRPM - desiredRPM) <= SPINUP_TOLERANCE_RPM) {
				// Right shooter is within tolerance. Spin indexer
				shooterBase.rightShooter.setIndexerSpeed(INDEXER_SPEED_WHILE_SHOOTING);
				conveyor.io.setConveyorSpeed(SHOOTING_CONVEYOR_SPEED);
			}
		} else {
			if (Math.abs(leftCurrentVelocityRPM - desiredRPM) <= SPINUP_TOLERANCE_RPM) {
				// Left shooter is within tolerance. Spin indexer
				shooterBase.leftShooter.setIndexerSpeed(INDEXER_SPEED_WHILE_SHOOTING);
				conveyor.io.setConveyorSpeed(SHOOTING_CONVEYOR_SPEED);
			}
			if (Math.abs(rightCurrentVelocityRPM - desiredRPM) <= SPINUP_TOLERANCE_RPM) {
				// Right shooter is within tolerance. Spin indexer
				shooterBase.rightShooter.setIndexerSpeed(INDEXER_SPEED_WHILE_SHOOTING);
				conveyor.io.setConveyorSpeed(SHOOTING_CONVEYOR_SPEED);
			}
		}
	}

	@Override
	public boolean isFinished() {
		return false;
	}

	@Override
	public void end(boolean interrupted) {

		// Stop everything that we used
		shooterBase.leftShooter.stopIndexer();
		shooterBase.leftShooter.stopFlywheel();
		shooterBase.rightShooter.stopIndexer();
		shooterBase.rightShooter.stopFlywheel();
		conveyor.io.stopConveyor();

//		RobotContainer.localizationSystem.syncPoses();
	}
}
